"""Changes

Revision ID: 2c28e9323942
Revises: 689b98f63ee8
Create Date: 2018-08-03 15:58:56.790426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c28e9323942'
down_revision = '689b98f63ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('begins', sa.Column('vertex_id', sa.Integer(), nullable=False))
    op.add_column('edges', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('edges', sa.Column('from_vertex', sa.Integer(), nullable=False))
    op.add_column('edges', sa.Column('to_vertex', sa.Integer(), nullable=False))
    op.add_column('ends', sa.Column('vertex_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ends', 'vertex_id')
    op.drop_column('edges', 'to_vertex')
    op.drop_column('edges', 'from_vertex')
    op.drop_column('edges', 'count')
    op.drop_column('begins', 'vertex_id')
    # ### end Alembic commands ###
