"""Changes

Revision ID: 5bd841a640e1
Revises: c268574ea4ce
Create Date: 2018-08-03 16:19:26.073490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd841a640e1'
down_revision = 'c268574ea4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
