"""Changes

Revision ID: c268574ea4ce
Revises: 2c28e9323942
Create Date: 2018-08-03 16:10:09.986829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c268574ea4ce'
down_revision = '2c28e9323942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
